NAME: "Mail Service"
ENVIRONMENT: "production"

LOG:
  LEVEL: DEBUG
  COLOR: true

WEB:
  HOST: 0.0.0.0
  PORT: 10000

DB:
  HOST: 127.0.0.1
  PORT: 5432
  USERNAME: thanhpp
  PASSWORD: testthanhpp
  DATABASE: mailservice

AUTH:
  JWKS_URL: "https://genome.vinbigdata.org/user/.well-known/jwks"
  AUDIENCES: 
    - user
    - openid
  ISSUERS:
    - https://genome.vinbigdata.org/user
  PURPOSE: access

# IF KEY IS CHANGED, OLD ENCRYPTED PASSWORDS WILL BE UNABLE TO DECRYPT 
# KEY MUST BE 16/24/32 bytes
ENCRYPTKEYPATH: ./key.txt 